/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dedupeer.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Chunk implements org.apache.thrift.TBase<Chunk, Chunk._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Chunk");

  private static final org.apache.thrift.protocol.TField FILE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("fileID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CHUNK_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("chunkNumber", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField INDEX_FIELD_DESC = new org.apache.thrift.protocol.TField("index", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField LENGTH_FIELD_DESC = new org.apache.thrift.protocol.TField("length", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField STRONG_HASH_FIELD_DESC = new org.apache.thrift.protocol.TField("strongHash", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField WEAK_HASH_FIELD_DESC = new org.apache.thrift.protocol.TField("weakHash", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField PFILE_FIELD_DESC = new org.apache.thrift.protocol.TField("pfile", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField PCHUNK_FIELD_DESC = new org.apache.thrift.protocol.TField("pchunk", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField DESTINATION_FIELD_DESC = new org.apache.thrift.protocol.TField("destination", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("content", org.apache.thrift.protocol.TType.STRING, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ChunkStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ChunkTupleSchemeFactory());
  }

  public String fileID; // required
  public String chunkNumber; // required
  public String index; // required
  public String length; // required
  public String strongHash; // optional
  public String weakHash; // optional
  public String pfile; // optional
  public String pchunk; // optional
  public String destination; // optional
  public ByteBuffer content; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FILE_ID((short)1, "fileID"),
    CHUNK_NUMBER((short)2, "chunkNumber"),
    INDEX((short)3, "index"),
    LENGTH((short)4, "length"),
    STRONG_HASH((short)5, "strongHash"),
    WEAK_HASH((short)6, "weakHash"),
    PFILE((short)7, "pfile"),
    PCHUNK((short)8, "pchunk"),
    DESTINATION((short)9, "destination"),
    CONTENT((short)10, "content");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FILE_ID
          return FILE_ID;
        case 2: // CHUNK_NUMBER
          return CHUNK_NUMBER;
        case 3: // INDEX
          return INDEX;
        case 4: // LENGTH
          return LENGTH;
        case 5: // STRONG_HASH
          return STRONG_HASH;
        case 6: // WEAK_HASH
          return WEAK_HASH;
        case 7: // PFILE
          return PFILE;
        case 8: // PCHUNK
          return PCHUNK;
        case 9: // DESTINATION
          return DESTINATION;
        case 10: // CONTENT
          return CONTENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.STRONG_HASH,_Fields.WEAK_HASH,_Fields.PFILE,_Fields.PCHUNK,_Fields.DESTINATION,_Fields.CONTENT};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILE_ID, new org.apache.thrift.meta_data.FieldMetaData("fileID", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CHUNK_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("chunkNumber", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INDEX, new org.apache.thrift.meta_data.FieldMetaData("index", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LENGTH, new org.apache.thrift.meta_data.FieldMetaData("length", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STRONG_HASH, new org.apache.thrift.meta_data.FieldMetaData("strongHash", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.WEAK_HASH, new org.apache.thrift.meta_data.FieldMetaData("weakHash", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PFILE, new org.apache.thrift.meta_data.FieldMetaData("pfile", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PCHUNK, new org.apache.thrift.meta_data.FieldMetaData("pchunk", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DESTINATION, new org.apache.thrift.meta_data.FieldMetaData("destination", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CONTENT, new org.apache.thrift.meta_data.FieldMetaData("content", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Chunk.class, metaDataMap);
  }

  public Chunk() {
  }

  public Chunk(
    String fileID,
    String chunkNumber,
    String index,
    String length)
  {
    this();
    this.fileID = fileID;
    this.chunkNumber = chunkNumber;
    this.index = index;
    this.length = length;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Chunk(Chunk other) {
    if (other.isSetFileID()) {
      this.fileID = other.fileID;
    }
    if (other.isSetChunkNumber()) {
      this.chunkNumber = other.chunkNumber;
    }
    if (other.isSetIndex()) {
      this.index = other.index;
    }
    if (other.isSetLength()) {
      this.length = other.length;
    }
    if (other.isSetStrongHash()) {
      this.strongHash = other.strongHash;
    }
    if (other.isSetWeakHash()) {
      this.weakHash = other.weakHash;
    }
    if (other.isSetPfile()) {
      this.pfile = other.pfile;
    }
    if (other.isSetPchunk()) {
      this.pchunk = other.pchunk;
    }
    if (other.isSetDestination()) {
      this.destination = other.destination;
    }
    if (other.isSetContent()) {
      this.content = org.apache.thrift.TBaseHelper.copyBinary(other.content);
;
    }
  }

  public Chunk deepCopy() {
    return new Chunk(this);
  }

  @Override
  public void clear() {
    this.fileID = null;
    this.chunkNumber = null;
    this.index = null;
    this.length = null;
    this.strongHash = null;
    this.weakHash = null;
    this.pfile = null;
    this.pchunk = null;
    this.destination = null;
    this.content = null;
  }

  public String getFileID() {
    return this.fileID;
  }

  public Chunk setFileID(String fileID) {
    this.fileID = fileID;
    return this;
  }

  public void unsetFileID() {
    this.fileID = null;
  }

  /** Returns true if field fileID is set (has been assigned a value) and false otherwise */
  public boolean isSetFileID() {
    return this.fileID != null;
  }

  public void setFileIDIsSet(boolean value) {
    if (!value) {
      this.fileID = null;
    }
  }

  public String getChunkNumber() {
    return this.chunkNumber;
  }

  public Chunk setChunkNumber(String chunkNumber) {
    this.chunkNumber = chunkNumber;
    return this;
  }

  public void unsetChunkNumber() {
    this.chunkNumber = null;
  }

  /** Returns true if field chunkNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetChunkNumber() {
    return this.chunkNumber != null;
  }

  public void setChunkNumberIsSet(boolean value) {
    if (!value) {
      this.chunkNumber = null;
    }
  }

  public String getIndex() {
    return this.index;
  }

  public Chunk setIndex(String index) {
    this.index = index;
    return this;
  }

  public void unsetIndex() {
    this.index = null;
  }

  /** Returns true if field index is set (has been assigned a value) and false otherwise */
  public boolean isSetIndex() {
    return this.index != null;
  }

  public void setIndexIsSet(boolean value) {
    if (!value) {
      this.index = null;
    }
  }

  public String getLength() {
    return this.length;
  }

  public Chunk setLength(String length) {
    this.length = length;
    return this;
  }

  public void unsetLength() {
    this.length = null;
  }

  /** Returns true if field length is set (has been assigned a value) and false otherwise */
  public boolean isSetLength() {
    return this.length != null;
  }

  public void setLengthIsSet(boolean value) {
    if (!value) {
      this.length = null;
    }
  }

  public String getStrongHash() {
    return this.strongHash;
  }

  public Chunk setStrongHash(String strongHash) {
    this.strongHash = strongHash;
    return this;
  }

  public void unsetStrongHash() {
    this.strongHash = null;
  }

  /** Returns true if field strongHash is set (has been assigned a value) and false otherwise */
  public boolean isSetStrongHash() {
    return this.strongHash != null;
  }

  public void setStrongHashIsSet(boolean value) {
    if (!value) {
      this.strongHash = null;
    }
  }

  public String getWeakHash() {
    return this.weakHash;
  }

  public Chunk setWeakHash(String weakHash) {
    this.weakHash = weakHash;
    return this;
  }

  public void unsetWeakHash() {
    this.weakHash = null;
  }

  /** Returns true if field weakHash is set (has been assigned a value) and false otherwise */
  public boolean isSetWeakHash() {
    return this.weakHash != null;
  }

  public void setWeakHashIsSet(boolean value) {
    if (!value) {
      this.weakHash = null;
    }
  }

  public String getPfile() {
    return this.pfile;
  }

  public Chunk setPfile(String pfile) {
    this.pfile = pfile;
    return this;
  }

  public void unsetPfile() {
    this.pfile = null;
  }

  /** Returns true if field pfile is set (has been assigned a value) and false otherwise */
  public boolean isSetPfile() {
    return this.pfile != null;
  }

  public void setPfileIsSet(boolean value) {
    if (!value) {
      this.pfile = null;
    }
  }

  public String getPchunk() {
    return this.pchunk;
  }

  public Chunk setPchunk(String pchunk) {
    this.pchunk = pchunk;
    return this;
  }

  public void unsetPchunk() {
    this.pchunk = null;
  }

  /** Returns true if field pchunk is set (has been assigned a value) and false otherwise */
  public boolean isSetPchunk() {
    return this.pchunk != null;
  }

  public void setPchunkIsSet(boolean value) {
    if (!value) {
      this.pchunk = null;
    }
  }

  public String getDestination() {
    return this.destination;
  }

  public Chunk setDestination(String destination) {
    this.destination = destination;
    return this;
  }

  public void unsetDestination() {
    this.destination = null;
  }

  /** Returns true if field destination is set (has been assigned a value) and false otherwise */
  public boolean isSetDestination() {
    return this.destination != null;
  }

  public void setDestinationIsSet(boolean value) {
    if (!value) {
      this.destination = null;
    }
  }

  public byte[] getContent() {
    setContent(org.apache.thrift.TBaseHelper.rightSize(content));
    return content == null ? null : content.array();
  }

  public ByteBuffer bufferForContent() {
    return content;
  }

  public Chunk setContent(byte[] content) {
    setContent(content == null ? (ByteBuffer)null : ByteBuffer.wrap(content));
    return this;
  }

  public Chunk setContent(ByteBuffer content) {
    this.content = content;
    return this;
  }

  public void unsetContent() {
    this.content = null;
  }

  /** Returns true if field content is set (has been assigned a value) and false otherwise */
  public boolean isSetContent() {
    return this.content != null;
  }

  public void setContentIsSet(boolean value) {
    if (!value) {
      this.content = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FILE_ID:
      if (value == null) {
        unsetFileID();
      } else {
        setFileID((String)value);
      }
      break;

    case CHUNK_NUMBER:
      if (value == null) {
        unsetChunkNumber();
      } else {
        setChunkNumber((String)value);
      }
      break;

    case INDEX:
      if (value == null) {
        unsetIndex();
      } else {
        setIndex((String)value);
      }
      break;

    case LENGTH:
      if (value == null) {
        unsetLength();
      } else {
        setLength((String)value);
      }
      break;

    case STRONG_HASH:
      if (value == null) {
        unsetStrongHash();
      } else {
        setStrongHash((String)value);
      }
      break;

    case WEAK_HASH:
      if (value == null) {
        unsetWeakHash();
      } else {
        setWeakHash((String)value);
      }
      break;

    case PFILE:
      if (value == null) {
        unsetPfile();
      } else {
        setPfile((String)value);
      }
      break;

    case PCHUNK:
      if (value == null) {
        unsetPchunk();
      } else {
        setPchunk((String)value);
      }
      break;

    case DESTINATION:
      if (value == null) {
        unsetDestination();
      } else {
        setDestination((String)value);
      }
      break;

    case CONTENT:
      if (value == null) {
        unsetContent();
      } else {
        setContent((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FILE_ID:
      return getFileID();

    case CHUNK_NUMBER:
      return getChunkNumber();

    case INDEX:
      return getIndex();

    case LENGTH:
      return getLength();

    case STRONG_HASH:
      return getStrongHash();

    case WEAK_HASH:
      return getWeakHash();

    case PFILE:
      return getPfile();

    case PCHUNK:
      return getPchunk();

    case DESTINATION:
      return getDestination();

    case CONTENT:
      return getContent();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FILE_ID:
      return isSetFileID();
    case CHUNK_NUMBER:
      return isSetChunkNumber();
    case INDEX:
      return isSetIndex();
    case LENGTH:
      return isSetLength();
    case STRONG_HASH:
      return isSetStrongHash();
    case WEAK_HASH:
      return isSetWeakHash();
    case PFILE:
      return isSetPfile();
    case PCHUNK:
      return isSetPchunk();
    case DESTINATION:
      return isSetDestination();
    case CONTENT:
      return isSetContent();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Chunk)
      return this.equals((Chunk)that);
    return false;
  }

  public boolean equals(Chunk that) {
    if (that == null)
      return false;

    boolean this_present_fileID = true && this.isSetFileID();
    boolean that_present_fileID = true && that.isSetFileID();
    if (this_present_fileID || that_present_fileID) {
      if (!(this_present_fileID && that_present_fileID))
        return false;
      if (!this.fileID.equals(that.fileID))
        return false;
    }

    boolean this_present_chunkNumber = true && this.isSetChunkNumber();
    boolean that_present_chunkNumber = true && that.isSetChunkNumber();
    if (this_present_chunkNumber || that_present_chunkNumber) {
      if (!(this_present_chunkNumber && that_present_chunkNumber))
        return false;
      if (!this.chunkNumber.equals(that.chunkNumber))
        return false;
    }

    boolean this_present_index = true && this.isSetIndex();
    boolean that_present_index = true && that.isSetIndex();
    if (this_present_index || that_present_index) {
      if (!(this_present_index && that_present_index))
        return false;
      if (!this.index.equals(that.index))
        return false;
    }

    boolean this_present_length = true && this.isSetLength();
    boolean that_present_length = true && that.isSetLength();
    if (this_present_length || that_present_length) {
      if (!(this_present_length && that_present_length))
        return false;
      if (!this.length.equals(that.length))
        return false;
    }

    boolean this_present_strongHash = true && this.isSetStrongHash();
    boolean that_present_strongHash = true && that.isSetStrongHash();
    if (this_present_strongHash || that_present_strongHash) {
      if (!(this_present_strongHash && that_present_strongHash))
        return false;
      if (!this.strongHash.equals(that.strongHash))
        return false;
    }

    boolean this_present_weakHash = true && this.isSetWeakHash();
    boolean that_present_weakHash = true && that.isSetWeakHash();
    if (this_present_weakHash || that_present_weakHash) {
      if (!(this_present_weakHash && that_present_weakHash))
        return false;
      if (!this.weakHash.equals(that.weakHash))
        return false;
    }

    boolean this_present_pfile = true && this.isSetPfile();
    boolean that_present_pfile = true && that.isSetPfile();
    if (this_present_pfile || that_present_pfile) {
      if (!(this_present_pfile && that_present_pfile))
        return false;
      if (!this.pfile.equals(that.pfile))
        return false;
    }

    boolean this_present_pchunk = true && this.isSetPchunk();
    boolean that_present_pchunk = true && that.isSetPchunk();
    if (this_present_pchunk || that_present_pchunk) {
      if (!(this_present_pchunk && that_present_pchunk))
        return false;
      if (!this.pchunk.equals(that.pchunk))
        return false;
    }

    boolean this_present_destination = true && this.isSetDestination();
    boolean that_present_destination = true && that.isSetDestination();
    if (this_present_destination || that_present_destination) {
      if (!(this_present_destination && that_present_destination))
        return false;
      if (!this.destination.equals(that.destination))
        return false;
    }

    boolean this_present_content = true && this.isSetContent();
    boolean that_present_content = true && that.isSetContent();
    if (this_present_content || that_present_content) {
      if (!(this_present_content && that_present_content))
        return false;
      if (!this.content.equals(that.content))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Chunk other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Chunk typedOther = (Chunk)other;

    lastComparison = Boolean.valueOf(isSetFileID()).compareTo(typedOther.isSetFileID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileID, typedOther.fileID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetChunkNumber()).compareTo(typedOther.isSetChunkNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChunkNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.chunkNumber, typedOther.chunkNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIndex()).compareTo(typedOther.isSetIndex());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIndex()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.index, typedOther.index);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLength()).compareTo(typedOther.isSetLength());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLength()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.length, typedOther.length);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStrongHash()).compareTo(typedOther.isSetStrongHash());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStrongHash()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.strongHash, typedOther.strongHash);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWeakHash()).compareTo(typedOther.isSetWeakHash());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWeakHash()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.weakHash, typedOther.weakHash);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPfile()).compareTo(typedOther.isSetPfile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPfile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pfile, typedOther.pfile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPchunk()).compareTo(typedOther.isSetPchunk());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPchunk()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pchunk, typedOther.pchunk);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDestination()).compareTo(typedOther.isSetDestination());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestination()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destination, typedOther.destination);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetContent()).compareTo(typedOther.isSetContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.content, typedOther.content);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Chunk(");
    boolean first = true;

    sb.append("fileID:");
    if (this.fileID == null) {
      sb.append("null");
    } else {
      sb.append(this.fileID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("chunkNumber:");
    if (this.chunkNumber == null) {
      sb.append("null");
    } else {
      sb.append(this.chunkNumber);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("index:");
    if (this.index == null) {
      sb.append("null");
    } else {
      sb.append(this.index);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("length:");
    if (this.length == null) {
      sb.append("null");
    } else {
      sb.append(this.length);
    }
    first = false;
    if (isSetStrongHash()) {
      if (!first) sb.append(", ");
      sb.append("strongHash:");
      if (this.strongHash == null) {
        sb.append("null");
      } else {
        sb.append(this.strongHash);
      }
      first = false;
    }
    if (isSetWeakHash()) {
      if (!first) sb.append(", ");
      sb.append("weakHash:");
      if (this.weakHash == null) {
        sb.append("null");
      } else {
        sb.append(this.weakHash);
      }
      first = false;
    }
    if (isSetPfile()) {
      if (!first) sb.append(", ");
      sb.append("pfile:");
      if (this.pfile == null) {
        sb.append("null");
      } else {
        sb.append(this.pfile);
      }
      first = false;
    }
    if (isSetPchunk()) {
      if (!first) sb.append(", ");
      sb.append("pchunk:");
      if (this.pchunk == null) {
        sb.append("null");
      } else {
        sb.append(this.pchunk);
      }
      first = false;
    }
    if (isSetDestination()) {
      if (!first) sb.append(", ");
      sb.append("destination:");
      if (this.destination == null) {
        sb.append("null");
      } else {
        sb.append(this.destination);
      }
      first = false;
    }
    if (isSetContent()) {
      if (!first) sb.append(", ");
      sb.append("content:");
      if (this.content == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.content, sb);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (fileID == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'fileID' was not present! Struct: " + toString());
    }
    if (chunkNumber == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'chunkNumber' was not present! Struct: " + toString());
    }
    if (index == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'index' was not present! Struct: " + toString());
    }
    if (length == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'length' was not present! Struct: " + toString());
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ChunkStandardSchemeFactory implements SchemeFactory {
    public ChunkStandardScheme getScheme() {
      return new ChunkStandardScheme();
    }
  }

  private static class ChunkStandardScheme extends StandardScheme<Chunk> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Chunk struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FILE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fileID = iprot.readString();
              struct.setFileIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CHUNK_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.chunkNumber = iprot.readString();
              struct.setChunkNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // INDEX
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.index = iprot.readString();
              struct.setIndexIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LENGTH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.length = iprot.readString();
              struct.setLengthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // STRONG_HASH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.strongHash = iprot.readString();
              struct.setStrongHashIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // WEAK_HASH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.weakHash = iprot.readString();
              struct.setWeakHashIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // PFILE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pfile = iprot.readString();
              struct.setPfileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // PCHUNK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pchunk = iprot.readString();
              struct.setPchunkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // DESTINATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.destination = iprot.readString();
              struct.setDestinationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.content = iprot.readBinary();
              struct.setContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Chunk struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.fileID != null) {
        oprot.writeFieldBegin(FILE_ID_FIELD_DESC);
        oprot.writeString(struct.fileID);
        oprot.writeFieldEnd();
      }
      if (struct.chunkNumber != null) {
        oprot.writeFieldBegin(CHUNK_NUMBER_FIELD_DESC);
        oprot.writeString(struct.chunkNumber);
        oprot.writeFieldEnd();
      }
      if (struct.index != null) {
        oprot.writeFieldBegin(INDEX_FIELD_DESC);
        oprot.writeString(struct.index);
        oprot.writeFieldEnd();
      }
      if (struct.length != null) {
        oprot.writeFieldBegin(LENGTH_FIELD_DESC);
        oprot.writeString(struct.length);
        oprot.writeFieldEnd();
      }
      if (struct.strongHash != null) {
        if (struct.isSetStrongHash()) {
          oprot.writeFieldBegin(STRONG_HASH_FIELD_DESC);
          oprot.writeString(struct.strongHash);
          oprot.writeFieldEnd();
        }
      }
      if (struct.weakHash != null) {
        if (struct.isSetWeakHash()) {
          oprot.writeFieldBegin(WEAK_HASH_FIELD_DESC);
          oprot.writeString(struct.weakHash);
          oprot.writeFieldEnd();
        }
      }
      if (struct.pfile != null) {
        if (struct.isSetPfile()) {
          oprot.writeFieldBegin(PFILE_FIELD_DESC);
          oprot.writeString(struct.pfile);
          oprot.writeFieldEnd();
        }
      }
      if (struct.pchunk != null) {
        if (struct.isSetPchunk()) {
          oprot.writeFieldBegin(PCHUNK_FIELD_DESC);
          oprot.writeString(struct.pchunk);
          oprot.writeFieldEnd();
        }
      }
      if (struct.destination != null) {
        if (struct.isSetDestination()) {
          oprot.writeFieldBegin(DESTINATION_FIELD_DESC);
          oprot.writeString(struct.destination);
          oprot.writeFieldEnd();
        }
      }
      if (struct.content != null) {
        if (struct.isSetContent()) {
          oprot.writeFieldBegin(CONTENT_FIELD_DESC);
          oprot.writeBinary(struct.content);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ChunkTupleSchemeFactory implements SchemeFactory {
    public ChunkTupleScheme getScheme() {
      return new ChunkTupleScheme();
    }
  }

  private static class ChunkTupleScheme extends TupleScheme<Chunk> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Chunk struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.fileID);
      oprot.writeString(struct.chunkNumber);
      oprot.writeString(struct.index);
      oprot.writeString(struct.length);
      BitSet optionals = new BitSet();
      if (struct.isSetStrongHash()) {
        optionals.set(0);
      }
      if (struct.isSetWeakHash()) {
        optionals.set(1);
      }
      if (struct.isSetPfile()) {
        optionals.set(2);
      }
      if (struct.isSetPchunk()) {
        optionals.set(3);
      }
      if (struct.isSetDestination()) {
        optionals.set(4);
      }
      if (struct.isSetContent()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetStrongHash()) {
        oprot.writeString(struct.strongHash);
      }
      if (struct.isSetWeakHash()) {
        oprot.writeString(struct.weakHash);
      }
      if (struct.isSetPfile()) {
        oprot.writeString(struct.pfile);
      }
      if (struct.isSetPchunk()) {
        oprot.writeString(struct.pchunk);
      }
      if (struct.isSetDestination()) {
        oprot.writeString(struct.destination);
      }
      if (struct.isSetContent()) {
        oprot.writeBinary(struct.content);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Chunk struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.fileID = iprot.readString();
      struct.setFileIDIsSet(true);
      struct.chunkNumber = iprot.readString();
      struct.setChunkNumberIsSet(true);
      struct.index = iprot.readString();
      struct.setIndexIsSet(true);
      struct.length = iprot.readString();
      struct.setLengthIsSet(true);
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.strongHash = iprot.readString();
        struct.setStrongHashIsSet(true);
      }
      if (incoming.get(1)) {
        struct.weakHash = iprot.readString();
        struct.setWeakHashIsSet(true);
      }
      if (incoming.get(2)) {
        struct.pfile = iprot.readString();
        struct.setPfileIsSet(true);
      }
      if (incoming.get(3)) {
        struct.pchunk = iprot.readString();
        struct.setPchunkIsSet(true);
      }
      if (incoming.get(4)) {
        struct.destination = iprot.readString();
        struct.setDestinationIsSet(true);
      }
      if (incoming.get(5)) {
        struct.content = iprot.readBinary();
        struct.setContentIsSet(true);
      }
    }
  }

}

